### ISSUE TITLE
unicontroller complete list command line

### ISSUE THREAD

**Issue by maravento** [iamola/uniserver#1]
where is the complete list of commands to work for cmd with unicontroller.exe? (start/stop it, start it without the root password window, etc.)
thanks
PD: PD: I have only found [this](https://github.com/iamola/uniserver/blob/master/UniController/command_line_start_up.pas):
```
Parameters implemented by this procedure:
   start_apache // Start Apache server
   stop_apache  // Stop Apache server
   start_mysql  // Start MySQL server
   stop_mysql   // Stop MySQL server
   start_both   // Starts Apache and MySQL servers
   stop_both    // Stops Apache and  MySQL servers
```
And there is no information with /?

**Comment by sudeepjd** [comment]
Yes.. Those are what you have... The corresponding code for the command line parameters are in the below file.

https://github.com/iamola/uniserver/blob/master/UniController/command_line_start_up.pas
