### ISSUE TITLE
Cannot register for Community Forum

### ISSUE THREAD

**Issue by missenc** [iamola/uniserver#10]
Love the software, all!

However, I have tried many times over the last week to set up an account in Community Forum and I get an error message about failing the security check.  I'm pretty sure I got it right at least half the time.

Can you check this out?

Thans,

-- Cliff

**Comment by BeholdersEye** [comment]
Same here.

The two questions are:

"Countdown from 10 to 0, odd numbers only!"

and 

"What is our software's name"

For the first question I have tried every combination of 97531 imaginable.

For the second question I have tried every version of Uniform Server I can think of.

If "This is a security check to prevent automated programs from creating accounts." then what purpose does the google captcha underneath it serve?

**Comment by s-bourdon** [comment]
Fixed!
Thanks for bringing this to our attention!
