### ISSUE TITLE
X64 version>

### ISSUE THREAD

**Issue by JosiasVasquez** [iamola/uniserver#11]
I had some problems installing drupal with uniforme server because de php 32 bits, you help me a lot adding a php x64 version working with the uniforme server.

**Comment by s-bourdon** [comment]
I'll look into it!

**Comment by s-bourdon** [comment]
Done!
The latest version of Uniform Server requires a 64-bit version of Windows and can be found on SourceForge at https://sourceforge.net/projects/miniserver/
