### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by DiviCon** [iamola/uniserver#12]
Hola, yo estoy tratando de instalar Codeigniter 4 con composer, pero la instalación muestra el siguiente error:

![image](https://user-images.githubusercontent.com/101996033/212800467-213ea563-b1a4-493f-9edf-10e218385480.png)

**Comment by sudeepjd** [comment]
As per snapshot attached you need the php intl extension. This can be enabled from 
UniController -> PHP -> Edit Basic Modules -> PHP Modules Enable/Disable

The check **intl**

![image](https://user-images.githubusercontent.com/12654213/212809377-65d89a3d-2369-43b6-9c98-190787d046d6.png)

**Comment by DiviCon** [comment]
Hola, yo he activado esa opción pero aún siguen sin funcionar.

 Usted debería intentar y te podrás dar cuenta que persiste el problema.

**Comment by sudeepjd** [comment]
As you are using composer from the command line the intl extention needs to enabled in the php-cli.ini file as well as the php_production.ini
