### ISSUE TITLE
Trouble with Strawberry Perl

### ISSUE THREAD

**Issue by yarnik1** [iamola/uniserver#2]
Hello,
I'm having trouble with Strawberry Perl.
1. Extracted 14_0_2_ZeroXIV.exe
2. Extracted ZeroXIV_strawberry_perl_5_30_0_1.exe
3. Run http: //localhost/cgi-bin/test.pl, test_1.pl, test_2.pl - ok
4. Run http: //localhost/cgi-bin/test_3.pl, test_4.pl, test_5.pl - error
5. I am trying to install additional Perl modules using UniServerZ\core\perl\bin\cpan.bat, command "install CGI" and also get error

**Comment by sudeepjd** [comment]
Thanks for raising the issue. I have replies to this on the forum post. Request to please DM me so that we can resolve together.

**Comment by s-bourdon** [comment]
I know this is an old post, but if anybody else ends up here looking for an explanation, here it is:
https://www.perl.com/article/perl-and-cgi/#why-not-to-use-cgi

test_3.pl, test_4.pl and test_5.pl require the installation of CGI.pm, which was marked deprecated with Perl 5.20 and removed from Core with Perl 5.22
